import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Slider from "react-slick";
import NavbarComp from "../components/NavbarComp.js"
const inter = Inter({ subsets: ['latin'] })
const devid= Math.floor(Math.random() * 7);
import devotions from '../components/devotion.json'
import Image from 'next/image.js';
// const [showPosts, setshowPosts] = useState('')
const photos = [
  {
    name: 'photo 1',
    url: "https://media.istockphoto.com/id/1448439652/photo/the-brightly-rising-new-years-sunrise-and-the-cross-of-jesus-christ-and-jesus.jpg?b=1&s=170667a&w=0&k=20&c=CW5SWaCQBO6VwWN8TRvSB_CSAVuA6j_ogYRR-yZPcTI="
  },
  {
    name: 'photo 2',
    url: "https://media.istockphoto.com/id/1367357589/photo/red-heart-shaped-sky-at-sunset-beautiful-landscape-with-flowers-love-background-with-copy.jpg?b=1&s=170667a&w=0&k=20&c=jJW2nQ8MHiSnWVSTUulpBt3xFKUjL0B_KAkE_uc5Sz8="
  },
  {
    name: 'photo 3',
    url: "https://media.istockphoto.com/id/1444449094/photo/nativity-scene-birth-of-jesus-christ-with-manger-in-snowy-night-and-starry-sky-abstract.jpg?b=1&s=170667a&w=0&k=20&c=8H4K6KDy0D_GzVAOHGdCGYHSEGDhG8fcmBKuRCw_yso="
  }
]
const settings = {
  dots: true,
  fade: true,
  infinte: true,
  speed: 500,
  slidestoshow: 1,
  arrows: true,
  slidestoscroll: 1,
  className: "slides"
}

export default function Home() {
  // displayData = data.map(function(todo){
  //   return(
  //     <p key={todo.id}> {todo.title}</p>
  //   )
  // })
  // console.log(devotions[0]["devotions"])
  console.log(devotions.devotions[devid])
  
  return (
    <>
      <Head>
        <title>Christ App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="homeimg">
        <main className={styles.main} >
          <NavbarComp/>
          <div style={{ padding: 24 }}>
            <h1> Prayer Place</h1>
            <Slider{...settings}>
              {photos.map((photo => {
                return (
                  <div>
                    <img width="100%" src={photo.url} />
                  </div>
                )
              }))}
            </Slider>
           <div>
            <h1>Daily Bread</h1>
            <p><b>{devotions.devotions[devid].title}</b></p>
            <p>{devotions.devotions[devid].Scripture}</p>
            <p>{devotions.devotions[devid].message}</p>
            <p><b>Prayer</b></p>
            <p>{devotions.devotions[devid].prayer}</p>
            <p>This message was brought to you by: <a href= {devotions.devotions[devid].messageRef}>{devotions.devotions[devid].messageRef}</a></p>
           </div>
          </div>
        </main>
      </div>
    </>
  )
}
