import React from "react"
import NavbarComp from "../components/NavbarComp.js"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Card from "../components/Card.js"
//import top-tracks from "../pages/top-tracks.js"


export default function MusicWallPage() {

  const [tracks, setTracks] = React.useState([])

  React.useEffect(() => {
    fetch("/api/track-recommendations")
    .then((res) => res.json())
    .then((data) => {
      console.log(data)
      setTracks(data.tracks)
    })
  }, [])

    console.log(tracks)

    return (
      <>
        <Head>
          <title>... Music</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" /> 
        </Head>
        <main className={styles.main} class="home">
          <NavbarComp/>
          <div>
            <h1 class="label">Music Wall</h1>
          </div>
          <div className='music'>
            {tracks.map((track) => (
              <Card
              title={track.name}
              imgUrl={track.album.images[0].url}
              artists={track.artists.map((artist) => artist.name).join(", ")}
              link={track.external_urls.spotify}
              />
            ))}

            
          </div>
        </main>
      </>
    )
  }
  