import React from "react"
import NavbarComp from "../components/NavbarComp.js"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Card from "../components/Card.js"
import Col from 'react-bootstrap/Col';
import Row from 'react-bootstrap/Row';

//import top-tracks from "../pages/top-tracks.js"


export default function MusicWallPage() {

  const [tracks, setTracks] = React.useState([])

  React.useEffect(() => {
    fetch("/api/track-recommendations")
    .then((res) => res.json())
    .then((data) => {
      console.log(data)
      setTracks(data.tracks)
    })
  }, [])

    console.log(tracks)

{/* <div class="section group">
    <div class="col span_1_of_3">
        1
    </div>
    <div class="col span_1_of_3">
        2
    </div>
    <div class="col span_1_of_3">
        3
    </div>
</div> */}

    return (
      <>
        <Head>
          <title>... Music</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" /> 
        </Head>
        <main className={styles.main} class="home">
          <NavbarComp/>
          <div>
            <h1 class="label">Worship Wall</h1>
          </div>
          <div className='music'>
          <div class="container">      
          </div>
          <div class="container">
        </div>
          <Row xs={1} md={2} className="g-4">
            {tracks.map((track) => (
              <Col>
              <Card
              title={track.name}
              imgUrl={track.album.images[0].url}
              artists={track.artists.map((artist) => artist.name).join(", ")}
              link={track.external_urls.spotify}
              />
              </Col>
            ))}
          </Row>
            
          </div>
        </main>
      </>
    )
  }
  