import React from "react"
import NavbarComp from "../components/NavbarComp.js"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'


export default function MusicWallPage() {
    return (
      <>
        <Head>
          <title>... Music</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main} class="home">
          <NavbarComp/>
          <div>
            <h1 class="label">Music Wall</h1>
          </div>
        </main>
      </>
    )
  }
  