import React from "react"
import NavbarComp from "../components/NavbarComp.js"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'


export default function PrayerBinPage() {
    return (
      <>
        <Head>
          <title>Prayer Bin</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <NavbarComp/>
          <div class="pbinimg">
            <h1>Prayer Bin</h1>
            <p><i><b>"And pray in the Spirit on all occasions with all kinds of prayers and requests. With this in mind, be alert and always keep on praying for all the Lord’s people." Ephesians 6:18</b></i></p>
            <p><b>Dear brothers and sisters, life is tough, but our God is tougher. Although we are far apart, we are part of one body. You are loved not only by the Father, Son, and Spirit, but also by us, your family in Christ. That being said, please let us know how we can pray for you.</b></p>
          </div>
        </main>
      </>
    )
  }