import React from "react"
import NavbarComp from "../components/NavbarComp.js"
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import { useEffect,useState } from "react"






export default function PrayerWallPage() {
  
const [pr, setPr] = useState([])
  useEffect(()=>{
    fetch("/api/prayers")
    .then((res) =>{
      console.log(res)
        return res.json()
    })
    .then((data)=>{
      const prayers = data.map((prayer, index) => {
        console.log(prayer)
        console.log(index)
        if(index >= 0) {
          console.log("Prayer at 1,1")
          // console.log(prayer[1][0])
            return {

               prayer: prayer[1][0],
                timestamp: prayer[1][1]
            }
          }
        })
      // console.log("DATA",data)
      // console.log(prayer)
      // console.log(timestamp)
      setPr(prayers)
      // console.log(pr)
      
      //  console.log("DATA",data);
      //  data.array.forEach(element => {
        // const markup=`
        // <div class="bubble bubble-bottom-left">
        //       <div>
        //         <p>${element.PrayerRequest}</p>
               
        //       </div>
        //       <div class="time">
        //         <i>${element.Timestamp}</i>
        //       </div>`
      // })
      // return data
      })
      .catch((error)=>
      console.log("error", error))
    },[])
    console.log(pr)
  
    return (
      <>
        <Head>
          <title>Prayer Wall</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <NavbarComp/>
          <div class="pwallimg">
            <h1>Prayer Wall</h1>
            <p><i><b>"And Jesus answered them, 'Have faith in God. Truly, I say to you, whoever says to this mountain, "Be taken up and thrown into the sea," and does not doubt in his heart, but believes that what he says will come to pass, it will be done for him. Therefore I tell you, whatever you ask in prayer, believe that you have received it, and it will be yours. And whenever you stand praying, forgive, if you have anything against anyone, so that your Father also who is in heaven may forgive you your trespasses.'" Mark 11:22-25</b></i></p>
            <p><b>Brothers and sisters. Let us pray without ceasing.</b></p>
            <div>
              {pr.map((prayerObj) => {
                return <div>
                  <p>{prayerObj.prayer}</p>
                  <p>{prayerObj.timestamp}</p>
              </div>
              })}
            </div>
          </div>
        </main>
      </>
    )
}